from scrapy import Item, Field

class BBrefItem(Item):
    season = Field()
    league = Field() 
    team = Field()
    wins = Field()
    losses = Field()
    finish = Field()
    age = Field()
    height = Field()
    weight = Field()
    games = Field()
    mp = Field()
    fg = Field()
    fga = Field()
    fga_pct = Field()
    fg3 = Field()
    fg3a = Field()
    fg3_pct = Field()
    fg2 = Field()
    fg2a = Field()
    fg2_pct = Field()
    ft = Field()
    fta = Field()
    ft_pct = Field()
    orb = Field()
    drb = Field()
    trb = Field()
    ast = Field()
    stl = Field()
    blk = Field()
    tov = Field()
    pf = Field()
    pts = Field()
    
